import re
from transformers import pipeline

# ============================
# LOAD MODEL
# ============================

summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)


# ============================
# CLEAN TRANSCRIPT
# ============================

def clean_text(text):

    if not text:
        return ""

    bad_words = [
        "Translate", "Translation completed",
        "Hindi", "Kannada", "Tamil", "Telugu", "Malayalam",
        "YouTube", "Lecture", "Load Video",
        "Generate Subtitles", "Original Subtitle",
        "Translated Subtitle", "Generated by YouTube"
    ]

    for word in bad_words:
        text = text.replace(word, "")

    text = re.sub(r'\b(\w+)( \1\b)+', r'\1', text)
    text = re.sub(r'\s+', ' ', text)

    return text.strip()


# ============================
# FILTER SENTENCES
# ============================

def filter_sentences(text):

    sentences = text.split(".")

    clean_sentences = []

    for sentence in sentences:
        sentence = sentence.strip()

        if len(sentence.split()) > 6:
            clean_sentences.append(sentence)

    return ". ".join(clean_sentences)


# ============================
# SPLIT TEXT (BETTER CHUNKING)
# ============================

def split_text(text, chunk_size=120):

    words = text.split()
    chunks = []

    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i:i + chunk_size])
        chunks.append(chunk)

    return chunks


# ============================
# MAIN SUMMARY FUNCTION 🔥
# ============================

def generate_summary(text):

    if not text:
        return "No lecture text available."

    # STEP 1: Clean
    text = clean_text(text)

    # STEP 2: Filter junk
    text = filter_sentences(text)

    if len(text.split()) < 20:
        return "Not enough lecture text to summarize."

    # STEP 3: Chunking
    chunks = split_text(text)

    chunk_summaries = []

    for chunk in chunks:
        try:
            result = summarizer(
                chunk,
                max_length=120,
                min_length=40,
                do_sample=False
            )

            chunk_summaries.append(result[0]["summary_text"])

        except Exception as e:
            print("Skipping chunk:", e)

    # STEP 4: FINAL RE-SUMMARIZATION 🔥
    combined_text = " ".join(chunk_summaries)

    try:
        final = summarizer(
            combined_text,
            max_length=150,
            min_length=60,
            do_sample=False
        )

        final_summary = final[0]["summary_text"]

    except:
        final_summary = combined_text

    # STEP 5: FORMAT INTO NOTES 🔥
    sentences = final_summary.split(".")

    bullets = []
    for s in sentences:
        s = s.strip()
        if len(s) > 15:
            bullets.append("• " + s)

    return "\n".join(bullets)